apiVersion: v1
kind: Service
metadata:
  name: recruitment-service
  namespace: recruitment-app
  labels:
    app: recruitment-app

spec:
  type: NodePort

  selector:
    app: recruitment-app

  ports:
  - name: http
    port: 80
    targetPort: 3000
    nodePort: 30007
